[project]
name = "motrix-lab"
version = "0.3.0"
description = "A general-purpose machine learning architecture designed for robot training"
authors = [{ name = "Motphys", email = "developers@motphys.com" }]
requires-python = ">=3.12,<3.13"

[project.optional-dependencies]
docs = [
    "sphinx",
    "autodocsumm",
    "pydata-sphinx-theme",
    "myst-parser",
    "sphinx-copybutton",
    "sphinx-subfigure",
    "sphinxcontrib-video",
    "sphinx-togglebutton",
    "sphinx-design",
]

[tool.uv.workspace]
members = ["motrix_envs", "motrix_rl", "motrix_il"]

[tool.uv]
package = false
