[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "motrix-envs"
version = "0.3.0"
description = "Robot simulation environment library based on MotrixSim providing multi-task RL environments."
authors = [{ name = "Motphys", email = "developers@motphys.com" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = "Apache-2.0"
dependencies = [
    "motrixsim>=0.7.0",
]
